const SQ_VISITORS=[
 {name:'夏凪アオイ',eng:'NATSUNAGI AOI',role:'RAINBOW TIDE NAVIGATOR',img:'assets/sky-garden/01-attendant.webp',accent:'#31d8ff',quotes:['海も空も、今日は最高。ほら、もっとこっちにおいでよ。','虹が消える前に、一緒に写真撮ろ？','濡れるの気にしてたら、夏は楽しめないよ。','次の波、私と勝負してみる？','笑って。青空には、その顔がいちばん似合うから。']},
 {name:'ルシア・ノクティア',eng:'LUCIA NOCTIA',role:'MOON-HORNED TIDE PRINCESS',img:'assets/sky-garden/02-hare.webp',accent:'#8d67ff',quotes:['ふふ、角が気になる？　触るなら優しくしてね。','海辺の魔族だって、夏くらい思いきり遊びたいの。','翼が濡れても平気。今日は泳ぐって決めたから。','その視線、ちゃんと気づいてるよ？','次はもっと深いところまで行ってみる？']},
 {name:'紫藤レイナ',eng:'SHIDO REINA',role:'MIDNIGHT LOUNGE ICON',img:'assets/sky-garden/03-horn.webp',accent:'#b889ff',quotes:['騒がしい夜ね。私はここで眺めてるくらいがちょうどいい。','似合ってる？　なら、その一言だけで十分。','無理に喋らなくてもいいわ。静かな時間も嫌いじゃないから。','そんなに見てると、こっちが困るんだけど。','もう少しだけここにいて。席、空けてあるから。']},
 {name:'黒羽ミオ',eng:'KUROHA MIO',role:'EMERALD NIGHT FELINE',img:'assets/sky-garden/04-dancer.webp',accent:'#62e3b3',quotes:['夜景、きれいでしょ？　でも見すぎると私が拗ねるよ。','猫みたいって？　褒め言葉として受け取っておくね。','この街の夜は長いの。まだ帰るには早いよ。','ウインク一つで油断するなんて、かわいい。','次の景色も見せてあげる。ちゃんとついてきてね。']}
];
function burstPetals(n=16){for(let i=0;i<n;i++){const p=document.createElement('i');p.className='petal';p.style.left=(48+Math.random()*8)+'vw';p.style.top=(42+Math.random()*14)+'vh';p.style.setProperty('--dx',((Math.random()-.5)*95)+'vw');p.style.setProperty('--dy',((Math.random()-.2)*75)+'vh');p.style.animationDelay=(Math.random()*.12)+'s';document.body.appendChild(p);setTimeout(()=>p.remove(),1500)}}
function initGallery(){const modal=document.querySelector('.modal'),modalImg=modal?.querySelector('img');document.querySelectorAll('[data-modal-img]').forEach(el=>el.addEventListener('click',()=>{if(!modal)return;modalImg.src=el.dataset.modalImg;modal.classList.add('open')}));modal?.addEventListener('click',e=>{if(e.target===modal||e.target.tagName==='BUTTON')modal.classList.remove('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')modal?.classList.remove('open')})}
function ensureExtendedNav(){const nav=document.querySelector('.nav');if(!nav)return;const links=[['news.html','NEWS'],['music.html','MUSIC'],['staffcast.html','STAFF&CAST'],['onair.html','ON AIR']];links.forEach(([href,label])=>{if(!nav.querySelector(`a[href="${href}"]`)){const a=document.createElement('a');a.href=href;a.textContent=label;nav.appendChild(a)}});if(!document.getElementById('sg-nav-extra-style')){const s=document.createElement('style');s.id='sg-nav-extra-style';s.textContent=`.nav{max-width:72vw;overflow-x:auto;white-space:nowrap;scrollbar-width:none}.nav::-webkit-scrollbar{display:none}@media(max-width:840px){.nav{max-width:none;justify-content:flex-start;overflow-x:auto;padding:0 8px}.nav a{min-width:max-content;flex:0 0 auto}}`;document.head.appendChild(s)}}
function ensureHomePortal(){const portal=document.querySelector('.portal-strip');if(!portal)return;const items=[['news.html','NEWS','更新情報・サイトアーカイブ'],['music.html','MUSIC','4人のテーマ・コンセプト'],['staffcast.html','STAFF&CAST','プロジェクトクレジット'],['onair.html','ON AIR','Web公開・閲覧情報']];items.forEach(([href,title,sub])=>{if(!portal.querySelector(`a[href="${href}"]`)){const a=document.createElement('a');a.href=href;a.innerHTML=`<b>${title}</b><span>${sub}</span>`;portal.appendChild(a)}});const s=document.createElement('style');s.textContent=`@media(min-width:841px){.portal-strip{grid-template-columns:repeat(3,1fr)!important}}`;document.head.appendChild(s)}
function activateNav(){const file=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===file))}
let SQ_AUDIO=null;const SQ_VIDEO_VOICE_CACHE=new Map();
function playAudio(src){if(SQ_AUDIO)SQ_AUDIO.pause();SQ_AUDIO=new Audio(src);SQ_AUDIO.volume=.92;return SQ_AUDIO.play().catch(()=>{})}
async function playVoiceSample(index){if(index<0||index>=SQ_VISITORS.length)return;if(SQ_VIDEO_VOICE_CACHE.has(index)){return playAudio(SQ_VIDEO_VOICE_CACHE.get(index))}const n=String(index+1).padStart(2,'0');try{const r=await fetch(`assets/voice/voice-${n}.b64`);if(!r.ok)throw new Error(`voice ${n} ${r.status}`);const b64=(await r.text()).replace(/\s+/g,'');const mime=b64.startsWith('T2dnUw')?'audio/ogg':'audio/mpeg';const src=`data:${mime};base64,${b64}`;SQ_VIDEO_VOICE_CACHE.set(index,src);return playAudio(src)}catch(e){console.warn('Video voice sample unavailable',e)}}
function voiceLine(text){const index=SQ_VISITORS.findIndex(v=>v.quotes.includes(text));return playVoiceSample(index)}
document.addEventListener('DOMContentLoaded',()=>{ensureExtendedNav();ensureHomePortal();activateNav();initGallery()});
